---
title: "air_pollution"
output: html_document
---

#load library
```{r}
library("foreign")
#install.packages("readODS")
library("readODS")
#install.packages("benford.analysis") 
library("benford.analysis")
```

#read air quality obs and predictions
```{r}
#聿欣's annual data and the predicted value of each town
pred<-read_ods("C:/Users/gis/Downloads/complete_prediction_5(聿欣).xlsx.ods")
summary(pred)
head(pred)

#pred<-read.csv("C:/Users/gis/Downloads/complete_prediction_5.csv",header=F)

#pred2<-pred[-1,]
# pred2$V3<-as.numeric(as.character(pred2$V3))
# pred2$V14<-as.numeric(as.character(pred2$V14))
# pred2$V41<-as.numeric(as.character(pred2$V41))
# summary(pred2$V3)
# head(pred2)
```

#the correct town shp (金門縣, 金門縣 towncode 長度不一樣)
```{r}
#downloaded from https://data.gov.tw/dataset/7441
#C:\Users\gis\Documents\TAO\air_pollution/mapdata201911260954

TOWN_MOI2<-read_ods("C:/Users/gis/Documents/TAO/air_pollution/mapdata201911260954/TOWN_MOI_1081121.ods")

TOWN_MOI2<-TOWN_MOI2[,c("COUNTYNAME","TOWNNAME","TOWNCODE"
#"TOWNID","TOWNCODE","COUNTYNAME","TOWNNAME","TOWNENG","COUNTYID","COUNTYCODE"
)]
TOWN_MOI2$CT_ID<-paste(TOWN_MOI2$COUNTYNAME,TOWN_MOI2$TOWNNAME,sep = "")
head(TOWN_MOI2)
dim(TOWN_MOI2)
```

<!-- #check towncode -->
<!-- ```{r} -->
<!-- e<-extract.digits( TOWN_MOI2$towncode   ,number.of.digits = 7) -->
<!-- e10<-e$data.digits*10  -->
<!-- dim(e10 -->
<!--     ) -->
<!-- length(e10) -->
<!-- ``` -->

#read the air pollution IDs for each town
```{r}
#use spatial join in QGIS to get the air pollution IDs for each town
#C:\Users\gis\Documents\TAO\air_pollution\town_pollution_id.shp
town_pollution_id<-read.dbf("C:/Users/gis/Documents/TAO/air_pollution/mapdata201911260954/grid_join_town.dbf")
town_pollution_id2<-town_pollution_id[,c("TOWNID","TOWNCODE",   "TOWNENG","COUNTYID","COUNTYCODE","ID","X_MIN","X_MAX","Y_MIN","Y_MAX")]
head(town_pollution_id2)

#fix chinese 

head(TOWN_MOI2)
town_pollution_id2$TOWNCODE<-(as.character(town_pollution_id2$TOWNCODE))

town_pollution_id3<-merge(town_pollution_id2,TOWN_MOI2,by = "TOWNCODE" )
head(town_pollution_id3)
#TOWN_MOI2$towncode ends w zero
#save correct cols
#town_pollution_id4<-town_pollution_id3[!duplicated(town_pollution_id3[,c( "TOWNCODE","ID")]),]
```

```{r}
pred_town_pollution_id<-merge(pred ,town_pollution_id3,by = "ID",all = F)

dim(pred)
dim(town_pollution_id3)
dim(pred_town_pollution_id)

head(pred_town_pollution_id)

TOWNCODE<-c("")
Predict<-c("")
#df<-data.frame(TOWNCODE,Predict)
#df$TOWNCODE<-as.character(df$TOWNCODE)
#df$Predict<-as.numeric(as.character(df$Predict))
for (y in c(2006)) 
{
  pred_town_pollution_id_year_mean2006<-aggregate(pred_town_pollution_id[pred_town_pollution_id$year ==y,c("predict(lm_all_inter_complete_4, yt_data_1)")] ,by=   list(pred_town_pollution_id[pred_town_pollution_id$year==y,]$TOWNCODE ), mean)
  colnames(pred_town_pollution_id_year_mean2006)<-c("TOWNCODE",paste("Predict",y,sep = "_")      )
 # dim(pred_town_pollution_id_year_mean)
#  head(pred_town_pollution_id_year_mean)
 # df<-rbind(df,pred_town_pollution_id_year_mean)
}

for (y in c(2007:2015)) 
{
  pred_town_pollution_id_year_mean<-aggregate(pred_town_pollution_id[pred_town_pollution_id$year ==y,c("predict(lm_all_inter_complete_4, yt_data_1)")] ,by=   list(pred_town_pollution_id[pred_town_pollution_id$year==y,]$TOWNCODE ), mean)
  colnames(pred_town_pollution_id_year_mean)<-c("TOWNCODE",paste("Predict",y,sep = "_"))
      pred_town_pollution_id_year_mean2006<-merge(  pred_town_pollution_id_year_mean, pred_town_pollution_id_year_mean2006,by ="TOWNCODE")
      
 # dim(pred_town_pollution_id_year_mean)
#  head(pred_town_pollution_id_year_mean)
 # df<-rbind(df,pred_town_pollution_id_year_mean)
}
#df<-df[-1,]
#head(df)
pred_town_pollution_id_year_mean_final<-merge(town_pollution_id3[,c("TOWNCODE","TOWNID","TOWNENG","COUNTYID","COUNTYCODE","ID", "COUNTYNAME","TOWNNAME","CT_ID")],pred_town_pollution_id_year_mean2006,by="TOWNCODE")
head(pred_town_pollution_id_year_mean_final)
pred_town_pollution_id_year_mean_final$mean2006_2015<-(pred_town_pollution_id_year_mean_final$Predict_2006+pred_town_pollution_id_year_mean_final$Predict_2007+pred_town_pollution_id_year_mean_final$Predict_2008+pred_town_pollution_id_year_mean_final$Predict_2009+pred_town_pollution_id_year_mean_final$Predict_2010+pred_town_pollution_id_year_mean_final$Predict_2011+pred_town_pollution_id_year_mean_final$Predict_2012+pred_town_pollution_id_year_mean_final$Predict_2013+pred_town_pollution_id_year_mean_final$Predict_2014+pred_town_pollution_id_year_mean_final$Predict_2015 )/10
write.csv(pred_town_pollution_id_year_mean_final,file = "C:/Users/gis/Documents/TAO/air_pollution/pred_town_pollution_id_year_mean_final.csv")
```


<!-- #read the air pollution IDs for each town -->
<!-- ```{r} -->
<!-- #use join in ArcGIS to get the air pollution IDs for each town -->
<!-- #C:\Users\gis\Documents\TAO\air_pollution\town_pollution_id.shp -->
<!-- county_pollution_id<-read.dbf("C:/Users/gis/Documents/TAO/air_pollution/county_pollution_id.dbf") -->
<!-- #fix chinese  -->
<!-- town_shp<-read_ods("C:/Users/gis/Documents/TAO/air_pollution/鄉鎮界WGS84_SHP/鄉鎮界_WGS84.ods") -->
<!-- colnames(  town_shp)<-c("townid",      "towncode",    "countyname", "townname") -->
<!-- county_pollution_id2<-merge(county_pollution_id,town_shp,by  = "towncode" ) -->
<!-- #save correct cols -->
<!-- county_pollution_id<-county_pollution_id2[,c("towncode","townid.y","countyname.y","townname.y","ID" )] -->
<!-- colnames(county_pollution_id)<-c("towncode","townid","countyname","townname","ID") -->
<!-- head(county_pollution_id) -->
<!-- county_pollution_id[county_pollution_id$townname=="蘇澳鎮",] -->
<!-- county_pollution_id4<-county_pollution_id[!duplicated(county_pollution_id[,c( "towncode","ID")]),] -->
<!-- county_pollution_id4[county_pollution_id4$townname=="蘇澳鎮",] -->
<!-- county_pollution_id4<-county_pollution_id4[,c("towncode","countyname","townname","ID")] -->
<!-- write.csv(county_pollution_id4[,c("towncode","countyname","townname","ID")],file="C:/Users/gis/Documents/TAO/air_pollution/town_id.csv") -->
<!-- ``` -->

#get the air pollution value for each town
```{r}
# dim(pred)
# dim(county_pollution_id)
# dim(pred[!pred$ID %in% county_pollution_id$ID,])
# dim(county_pollution_id[!county_pollution_id$ID %in% pred$ID,])
#county_pollution_id2<-unique(county_pollution_id[,c("towncode")])




head(pred_county_pollution_id)
# #mean predicted value for each town in each year
#1000203     宜蘭縣   蘇澳鎮
for (y in c(2006:2015)) {
pred_county_pollution_id_year_mean<-aggregate(pred_county_pollution_id[pred_county_pollution_id$year==y,]$`predict(lm_all_inter_complete_4, yt_data_1)` ,       by=   list(pred_county_pollution_id[pred_county_pollution_id$year==y,]$towncode), mean)

colnames(pred_county_pollution_id_year_mean)<-c("towncode","predict(lm_all_inter_complete_4, yt_data_1)")
pred_county_pollution_id_year_mean$towncode<-as.numeric(as.character(pred_county_pollution_id_year_mean$towncode))
county_pollution_id5<-county_pollution_id4[,c("towncode","countyname","townname" )]

county_pollution_id5<-county_pollution_id5[!duplicated(county_pollution_id5[,c("towncode","countyname","townname")]),]
dim(county_pollution_id5)
head(county_pollution_id5)
county_pollution_id5$towncode<-as.numeric(as.character(county_pollution_id5$towncode))
pred_county_pollution_id_year_mean2<-merge(county_pollution_id5,pred_county_pollution_id_year_mean,by="towncode")

colnames(pred_county_pollution_id_year_mean2)<-c("towncode","countyname","townname","predict")
   write.csv(pred_county_pollution_id_year_mean2,file=paste("C:/Users/gis/Documents/TAO/air_pollution/town_pred_",y,".csv"))
                                                                                    
}

colnames(pred_county_pollution_id)<-c(colnames(pred_county_pollution_id)[1:90],"predict",colnames(pred_county_pollution_id)[92:94])

for (y in c(2006:2015)) {
pred_county_pollution_id_year_mean<-aggregate(pred_county_pollution_id[pred_county_pollution_id$year==y,c(17:91)] ,by=   list(pred_county_pollution_id[pred_county_pollution_id$year==y,]$towncode), mean)

colnames(pred_county_pollution_id_year_mean)<-c("towncode",colnames(pred_county_pollution_id[17:91]))

pred_county_pollution_id_year_mean$towncode<-as.numeric(as.character(pred_county_pollution_id_year_mean$towncode))
county_pollution_id5<-county_pollution_id4[,c("towncode","countyname","townname" )]

county_pollution_id5<-county_pollution_id5[!duplicated(county_pollution_id5[,c("towncode","countyname","townname")]),]
#dim(county_pollution_id5)
#head(county_pollution_id5)
county_pollution_id5$towncode<-as.numeric(as.character(county_pollution_id5$towncode))
pred_county_pollution_id_year_mean2<-merge(county_pollution_id5,pred_county_pollution_id_year_mean,by="towncode")

#colnames(pred_county_pollution_id_year_mean2)<-c("towncode","countyname","townname","predict")
   write.csv(pred_county_pollution_id_year_mean2,file=paste("C:/Users/gis/Documents/TAO/air_pollution/Town_air_pollution_predict/town_pred_",y,".csv"))
                                                                                    
}

#  pred_county_pollution_id_mean<-aggregate(pred_county_pollution_id$`predict(lm_all_inter_complete_4, yt_data_1)` ,       by=   list(pred_county_pollution_id$townid ), mean)
#   pred_county_pollution_id_mean2<-aggregate(pred_county_pollution_id$`predict(lm_all_inter_complete_4, yt_data_1)` ,       by=   list(pred_county_pollution_id$towncode  ), mean)
#   #pred_county_pollution_id_mean2$Group.1<- (as.character(pred_county_pollution_id_mean2$Group.1))
#  # pred_county_pollution_id_mean2<-merge(pred_county_pollution_id_mean2,town_shp,by.x=pred_county_pollution_id_mean2$Group.1,town_shp$`towncode,C,7`)
#   write.csv(pred_county_pollution_id_mean2,file="C:/Users/gis/Documents/TAO/air_pollution/pred2_county_pollution_id_mean2.csv")
# # head(pred_county_pollution_id_mean)
# #t<-data.frame(table(pred_county_pollution_id_mean$Group.1))
#  dim(pred_county_pollution_id_mean)
```


```{r}
pred2_county_pollution_id<-merge(pred2,county_pollution_id ,by.x= "V3",by.y= "ID"
                                 #,all=F
                                 )
dim(pred2)
dim(county_pollution_id)
dim(pred2_county_pollution_id)
 pred2_county_pollution_id_mean<-aggregate(pred2_county_pollution_id$V41,       by=   list(pred2_county_pollution_id$townid),
mean)
  pred2_county_pollution_id_mean$cate<-"<16"
    pred2_county_pollution_id_mean[pred2_county_pollution_id_mean$x<17  &   pred2_county_pollution_id_mean$x>=16,]$cate<-"16-17"
    pred2_county_pollution_id_mean[ pred2_county_pollution_id_mean$x>=17,]$cate<-">17"
  

    
  write.csv(pred2_county_pollution_id_mean,file="C:/Users/gis/Documents/TAO/air_pollution/pred2_county_pollution_id_mean.csv")
for (y in c(2006:2015)) {
#  pred2_county_pollution_id[pred2_county_pollution_id$V2==y,]
# pred2_county_pollution_id_mean<-aggregate(pred2_county_pollution_id$V41,       by=   list(pred2_county_pollution_id$townid),mean)
  
#  write.csv(pred2_county_pollution_id[pred2_county_pollution_id$V2==y,],file=paste("C:/Users/gis/Documents/TAO/air_pollution/",y,".csv"))
}
  save(pred2_county_pollution_id,file="C:/Users/gis/Documents/TAO/air_pollution/pred2_county_pollution_id.Rdata")
```





